version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:mariadb
    build:
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT_PASSWD: ${DB_ROOT_PASSWD}
        DB_USER: ${DB_USER}
        DB_USER_PASSWD: ${DB_USER_PASSWD}
      context: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  nginx:
    depends_on:
      - wordpress
    image: nginx:nginx
    container_name: nginx
    build:
      context: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    depends_on:
      - mariadb
      - redis                   #BONUS
    image: wordpress:wordpress
    container_name: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always

# BONUS
  redis:
    image: redis:redis
    container_name: redis
    build:
      context: requirements/bonus/redis
    networks:
      - inception
    restart: always

  portfolio:
    image: portfolio:portfolio
    container_name: portfolio
    build:
      context: requirements/bonus/portfolio
    ports:
      - 1234:1234
    restart: always

  adminer:
    depends_on:
      - mariadb
    image: adminer:adminer
    container_name: adminer
    build:
      context: requirements/bonus/adminer
    networks:
      - inception
    ports:
      - 1235:8000
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wordpress
      o: bind
